image: registry.cn-shanghai.aliyuncs.com/choerodon-tools/cibase:0.9.0

stages:
  - build
  - release

release:
  stage: release
  script:
    - chart_build

build:
  stage: build
  script:
    - sed -i "s/CI_COMMIT_TAG/${CI_COMMIT_TAG}/g" index.html
    - docker build -t ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG} .
    - docker push ${DOCKER_REGISTRY}/${GROUP_NAME}/${PROJECT_NAME}:${CI_COMMIT_TAG}

.auto_devops: &auto_devops |
  http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
  if [ "$http_status_code" != "200" ]; then
    cat .auto_devops.sh
    exit 1
  fi
  source .auto_devops.sh

before_script:
  - *auto_devops
